name: Build and publish APK

on:
  push:
    tags:
      - "*"
jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release-key.jks

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        run: |
          apksigner sign \
            --ks release-key.jks \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --out app-release-signed.apk \
            app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Verify signature
        run: apksigner verify --verbose app-release-signed.apk

      - name: Releasing using Hub
        uses: sangatdesai/release-apk@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          APP_FOLDER: app