name: Run Tests

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Load API key into local.properties
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo API_KEY=$API_KEY > local.properties

      - name: Run Unit Tests
        run: ./gradlew clean testDebug