name: Run Instrumentation Tests

on:
  push:
    branches:
      - main
jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Load API key into local.properties
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo API_KEY=$API_KEY > local.properties

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Fetch dependencies
        run: ./gradlew --no-daemon --stacktrace buildEnvironment

      - name: Assemble app and androidTest
        run: ./gradlew --no-daemon --stacktrace :app:assembleDebug :app:assembleAndroidTest

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          disable-animations: true
          emulator-options: -no-window -no-snapshot -no-boot-anim -camera-back none -camera-front none -gpu swiftshader_indirect -noaudio -qemu -m 2048
          script: ./gradlew --no-daemon --stacktrace :app:connectedDebugAndroidTest

      - name: Run Instrumentation Tests
        run: ./gradlew connectedDebugAndroidTest --no-daemon --stacktrace

      - name: Dump logcat
        if: always()
        run: adb logcat -d > logcat.txt || true

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-ui-test-reports
          path: |
            app/build/reports/androidTests/connected/**
            app/build/outputs/androidTest-results/connected/**
            logcat.txt
            retention-days: 7
