name: UI Test
on: [ push, pull_request ]

jobs:
  connected_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.34.0
        with:
          api-level: 35
          script: ./gradlew connectedCheck