name: Run Instrumentation Tests

on:
  push:
    branches:
      - main
jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Load API key into local.properties
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo API_KEY=$API_KEY > local.properties

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Fetch dependencies
        run: ./gradlew --no-daemon --stacktrace buildEnvironment

      - name: Assemble app and androidTest
        run: ./gradlew --no-daemon --stacktrace :app:assembleDebug :app:assembleAndroidTest

      - name: Run UI tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          disable-animations: true
          emulator-options: -no-window -no-snapshot -no-boot-anim -camera-back none -camera-front none -gpu swiftshader_indirect -accel off
          script: |
            adb start-server
            adb devices
            ./gradlew --no-daemon --stacktrace :app:assembleDebug :app:assembleAndroidTest
            ./gradlew --no-daemon --stacktrace :app:connectedDebugAndroidTest

      - name: Collect reports
        if: always()
        run: |
          mkdir -p artifacts
          cp -R app/build/reports/androidTests/connected artifacts/reports || true
          cp -R app/build/outputs/androidTest-results/connected artifacts/results || true
          adb logcat -d > artifacts/logcat.txt || true
          
          - name: Upload artifacts
            if: always()
            uses: actions/upload-artifact@v4
            with:
              name: android-ui-test-reports
              path: artifacts
              retention-days: 7
      
