name: Run Instrumentation Tests

on:
  push:
    branches:
      - test

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Load API key into local.properties
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo API_KEY=$API_KEY > local.properties

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Fetch dependencies
        run: ./gradlew --no-daemon --stacktrace buildEnvironment

      - name: Assemble app and androidTest
        run: ./gradlew --no-daemon --stacktrace :app:assembleDebug :app:assembleAndroidTest

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run UI tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          profile: pixel_4
          force-avd-creation: true
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -no-audio -no-snapshot -camera-back none -camera-front none -partition-size 2048
          disable-avd-cache: false
          script: |
            echo "Waiting for emulator to be ready..."
            adb wait-for-device
            echo "Emulator is running"
            
            # Wait for boot completion
            while [ "`adb shell getprop sys.boot_completed | tr -d '\r' `" != "1" ] ; do
              echo "Waiting for boot completion..."
              sleep 5
            done
            
            echo "Device is fully booted"
            adb devices
            adb shell settings put global window_animation_scale 0.0
            adb shell settings put global transition_animation_scale 0.0
            adb shell settings put global animator_duration_scale 0.0
            
            ./gradlew --no-daemon --stacktrace :app:connectedDebugAndroidTest

      - name: Collect reports
        if: always()
        run: |
          mkdir -p artifacts
          cp -R app/build/reports/androidTests/connected artifacts/reports || true
          cp -R app/build/outputs/androidTest-results/connected artifacts/results || true
          adb logcat -d > artifacts/logcat.txt || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-ui-test-reports
          path: artifacts
          retention-days: 7